numenta/htm.java

- .travis.yml
- build.gradle
- pom.xml
- src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java
Fixes #143 Fixed #143 Fix #143
> Network api work

- src/main/java/org/numenta/nupic/Connections.java
- src/main/java/org/numenta/nupic/algorithms/CLAClassifier.java
- src/main/java/org/numenta/nupic/encoders/CoordinateEncoder.java
- src/main/java/org/numenta/nupic/encoders/Encoder.java
- src/main/java/org/numenta/nupic/encoders/GeospatialCoordinateEncoder.java
- src/main/java/org/numenta/nupic/encoders/LogEncoder.java
- src/main/java/org/numenta/nupic/encoders/MultiEncoder.java
- src/main/java/org/numenta/nupic/encoders/PassThroughEncoder.java
- src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java
- src/main/java/org/numenta/nupic/model/DistalDendrite.java
- src/main/java/org/numenta/nupic/model/Pool.java
- src/main/java/org/numenta/nupic/model/Segment.java
- src/main/java/org/numenta/nupic/model/Synapse.java
- src/main/java/org/numenta/nupic/research/SpatialPooler.java
- src/main/java/org/numenta/nupic/research/TemporalMemory.java
- src/main/java/org/numenta/nupic/util/ArrayUtils.java
- src/test/java/org/numenta/nupic/encoders/LogEncoderTest.java
- src/test/java/org/numenta/nupic/encoders/RandomDistributedScalarEncoderTest.java
- vocabulary.dictionary
This fixes the entire list (those things that were found to be accurate and not acceptable) from (fixes #139). This also smooths out memory pressure from issue (fixes #169)
> Clean up & Initial profiling optimization

- src/main/java/org/numenta/nupic/algorithms/CLAClassifier.java
- src/main/java/org/numenta/nupic/algorithms/ClassifierResult.java
- src/test/java/org/numenta/nupic/algorithms/ClassifierResultTest.java
> Added convenience method to CLAClassifier

- build/phantom.txt
- src/main/java/org/numenta/nupic/encoders/AdaptiveScalarEncoder.java
- src/main/java/org/numenta/nupic/encoders/DeltaEncoder.java
- src/test/java/org/numenta/nupic/encoders/AdaptiveScalarEncoderTest.java
- src/test/java/org/numenta/nupic/encoders/DeltaEncoderTest.java
EDITED:  Fixes #91
Hi,
I have now completed at least basic coding for AdaptiveScalarEncoder and DeltaEncoder with it's tests. 
This is now ready for review and let me know if it is ready for merging with master branch. 
If there is any logical errors are there please let me know so that I can correct those.
Regards,
Sambit Gaan
> AdaptiveScalarEncoder and DeltaEncoder with respective tests

- .gitignore
- build.gradle
- pom.xml
- src/main/java/org/numenta/nupic/encoders/AdaptiveScalarEncoder.java
- src/main/java/org/numenta/nupic/encoders/CategoryEncoder.java
- src/main/java/org/numenta/nupic/encoders/Encoder.java
- src/main/java/org/numenta/nupic/encoders/LogEncoder.java
- src/main/java/org/numenta/nupic/encoders/MultiEncoder.java
- src/main/java/org/numenta/nupic/encoders/PassThroughEncoder.java
- src/main/java/org/numenta/nupic/encoders/RandomDistributedScalarEncoder.java
- src/main/java/org/numenta/nupic/encoders/SDRCategoryEncoder.java
- src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java
- src/test/java/org/numenta/nupic/encoders/CategoryEncoderTest.java
- src/test/java/org/numenta/nupic/encoders/SDRCategoryEncoderTest.java
- src/test/resources/logback-test.xml
Fixes #150, #151, #152, #154, #155 and lays foundation for related issues.
Note: there is no use of verbosity in the ``GeospatialCoordinateEncoder`` and so #153 can be closed.
> Introduced SLF4J for logging (w/ Logback in tests)

- src/jmh/java/org/numenta/nupic/benchmarks/AbstractAlgorithmBenchmark.java
- src/jmh/java/org/numenta/nupic/benchmarks/SpatialPoolerGlobalInhibitionBenchmark.java
- src/jmh/java/org/numenta/nupic/benchmarks/SpatialPoolerLocalInhibitionBenchmark.java
- src/jmh/java/org/numenta/nupic/benchmarks/TemporalMemoryBenchmark.java
> spaces instead of tabs (where was this hiding?)

- jdoc.sh
> Add benchmarks and examples to java doc generation src dirs

- README.md
> it's official

- src/main/java/org/numenta/nupic/algorithms/Anomaly.java
- src/main/java/org/numenta/nupic/algorithms/AnomalyLikelihoodMetrics.java
- src/main/java/org/numenta/nupic/algorithms/ClassifierResult.java
- src/test/java/org/numenta/nupic/algorithms/AnomalyLikelihoodMetricsTest.java
- src/test/java/org/numenta/nupic/algorithms/ClassifierResultTest.java
> Prep for Net API add copy methods to classes and add tests

- src/main/java/org/numenta/nupic/algorithms/Sample.java
> Samples need to be externally composable to use Anomaly module

- src/main/java/org/numenta/nupic/encoders/SparsePassThroughEncoder.java
- src/test/java/org/numenta/nupic/algorithms/ClassifierResultTest.java
- src/test/java/org/numenta/nupic/encoders/SparsePassThroughEncoderTest.java
> Adding logging to SparsePassThroughEncoder

- src/main/java/org/numenta/nupic/encoders/PassThroughEncoder.java
Found this that can be helpful http://stackoverflow.com/questions/943367/string-format-with-lazy-evaluation/14078904#14078904
Fixes #208
> PassThroughEncoder Logging + other improvements

- src/main/java/org/numenta/nupic/examples/network/NetworkAPIDemo.java
- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/network/Region.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
> fix for onComplete propagation

- build.gradle
- pom.xml
- src/main/java/org/numenta/nupic/examples/network/NetworkAPIDemo.java
> Test build is ok with repo publishing versions of build files

- src/main/java/org/numenta/nupic/network/sensor/SensorFlags.java
- src/test/java/org/numenta/nupic/network/sensor/HeaderTest.java
Fixes #240
Added "L" flag initialization and Corrected testProcessLearn()
> Fix for Learn flag oversight

- src/main/java/org/numenta/nupic/examples/qt/QuickTest.java
> Quick test fix

- .simplecov
- build.gradle
- pom.xml
- src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java
- src/test/java/org/numenta/nupic/util/MersenneTwisterFastTest.java
- src/test/java/org/numenta/nupic/util/MersenneTwisterTest.java
- vocabulary.dictionary
> Remove logging in main execution path

- src/main/java/org/numenta/nupic/network/sensor/HTMSensor.java
- src/test/java/org/numenta/nupic/network/sensor/HTMSensorTest.java
Fixes #249 
a check for not initialised encoders is more 
robust and verbose
> fixes #249:

- src/main/java/org/numenta/nupic/examples/cortical_io/FoxEatsDemo.java
- src/main/java/org/numenta/nupic/examples/cortical_io/FoxEatsDemoView.java
> Deleted personal cache to find error for new users, then fixed

- src/main/java/org/numenta/nupic/examples/cortical_io/FoxEatsDemo.java
> Slight tweak to inference output for last question - clean up

- CHANGELOG.md
- jdoc.sh
Fixes #262 
Adding CHANGLOG.md to project to phase in version planning after consult with @rhyolight
> Javadoc update

- CHANGELOG.md
Fixes #264
Update the changelog and java docs for new api change
> Updated Changelog & Docs

- .travis.yml
- src/main/java/org/numenta/nupic/Connections.java
- src/main/java/org/numenta/nupic/Parameters.java
- src/main/java/org/numenta/nupic/datagen/PatternMachine.java
- src/main/java/org/numenta/nupic/examples/napi/NetworkAPIDemo.java
- src/main/java/org/numenta/nupic/model/DistalDendrite.java
- src/main/java/org/numenta/nupic/model/ProximalDendrite.java
- src/main/java/org/numenta/nupic/model/Segment.java
- src/main/java/org/numenta/nupic/model/Synapse.java
- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/network/Network.java
- src/main/java/org/numenta/nupic/network/Region.java
- src/main/java/org/numenta/nupic/network/sensor/BatchedCsvStream.java
- src/main/java/org/numenta/nupic/network/sensor/CSVSource.java
- src/main/java/org/numenta/nupic/network/sensor/Publisher.java
- src/main/java/org/numenta/nupic/network/sensor/SensorFlags.java
- src/main/java/org/numenta/nupic/network/sensor/SensorParams.java
- src/main/java/org/numenta/nupic/util/ArrayUtils.java
- src/main/java/org/numenta/nupic/util/DecodeTuple.java
- src/main/java/org/numenta/nupic/util/Deque.java
- src/main/java/org/numenta/nupic/util/MersenneTwister.java
- src/main/java/org/numenta/nupic/util/MersenneTwisterFast.java
- vocabulary.dictionary
Fixes #267  
Added -Dmaven.test.failure.ignore=true
> Try to circumvent Coveralls problem

- build.gradle
- pom.xml
> Increment version for new release

- build.gradle
- pom.xml
* Removing local repo from pom.xml
* Removing cortical-fxwidgets from Dependencies
* Removing cortical-twitterutil from Dependencies
Fixes #287
> Dependencies - conflict with Maven

- pom.xml
Fixes #293 
Fixes #266
Fixed by @godin (Evgeny Mandrikov)
> Fix coverage report submission failure

- pom.xml
> Remove cortical dependency

- INSTALL.txt
> add simple install instructions

- build.gradle
- pom.xml
> Push up snapshots for new version prior to release

- src/main/java/org/numenta/nupic/model/Pool.java
- src/main/java/org/numenta/nupic/model/Segment.java
- src/main/java/org/numenta/nupic/model/Synapse.java
- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/network/ManualInput.java
- src/main/java/org/numenta/nupic/network/Network.java
- src/main/java/org/numenta/nupic/network/Region.java
- src/main/java/org/numenta/nupic/util/NamedTuple.java
- src/test/java/org/numenta/nupic/algorithms/SampleTest.java
- src/test/java/org/numenta/nupic/algorithms/TemporalMemoryTest.java
- src/test/java/org/numenta/nupic/integration/ExtensiveTemporalMemoryTest.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
- src/test/java/org/numenta/nupic/network/ManualInputTest.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
- src/test/java/org/numenta/nupic/network/RegionTest.java
- src/test/java/org/numenta/nupic/util/NamedTupleTest.java
- vocabulary.dictionary
Fixes #292 
Fixes #305 
Fixes #306 
Fixes #308
> 0.6.2 snapshot release

- build.gradle
- pom.xml
> update release files

- build.gradle
- pom.xml
- src/test/java/org/numenta/nupic/network/LayerTest.java
> 0.6.3 snapshot

- src/main/java/org/numenta/nupic/network/Network.java
- src/main/java/org/numenta/nupic/network/Region.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
- vocabulary.dictionary
> Synchronous compute fix

- build.gradle
- pom.xml
- src/main/java/org/numenta/nupic/network/Layer.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
- vocabulary.dictionary
> Prep v0.6.3

- src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
> Fix computing flat index in SpatialPooler#getNeighborsND

- .classpath
- .gitignore
> Add correct classpath back into project

- build.gradle
- pom.xml
- src/main/java/org/numenta/nupic/SDR.java
- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/util/FlatArrayMatrix.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
- src/test/java/org/numenta/nupic/network/sensor/HTMSensorTest.java
Fixes #338 
Also prep snapshots
> Slightchange

- src/main/java/org/numenta/nupic/Connections.java
- src/main/java/org/numenta/nupic/algorithms/PASpatialPooler.java
- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/network/Network.java
- src/main/java/org/numenta/nupic/network/PALayer.java
- src/test/java/org/numenta/nupic/network/PALayerTest.java
> Added PASpatialPooler, PALayer, and adjusted Layer.java for inheritance

- src/main/java/org/numenta/nupic/algorithms/PASpatialPooler.java
- src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/network/PALayer.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
- src/test/java/org/numenta/nupic/network/PALayerTest.java
- vocabulary.dictionary
> Added code to better handle inter-region dimension calculations

- src/main/java/org/numenta/nupic/network/PALayer.java
- vocabulary.dictionary
> Added PALayer documentation

- src/test/java/org/numenta/nupic/encoders/MultiEncoderTest.java
- src/test/java/org/numenta/nupic/network/PALayerTest.java
Fixes #351
Remove a couple annoyances and embellish test
> Remove compiler warnings from classes

- build.gradle
- pom.xml
- src/test/java/org/numenta/nupic/network/LayerTest.java
- vocabulary.dictionary
> prep for new version

- src/main/java/org/numenta/nupic/network/Layer.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
> Fix for generic observable execution order

- src/main/java/org/numenta/nupic/Parameters.java
- src/main/java/org/numenta/nupic/encoders/DateEncoder.java
- src/main/java/org/numenta/nupic/encoders/MultiEncoderAssembler.java
- src/test/java/org/numenta/nupic/encoders/DateEncoderTest.java
Fixes #358 (but better). Upgraded dayOfWeek to use fractional days. Removed now-redundant hourOfDay.
> Fixed dayOfWeek to use fractional value, removed hourOfWeek

- src/main/java/org/numenta/nupic/network/Layer.java
- vocabulary.dictionary
> fix documentation

- src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
- src/main/java/org/numenta/nupic/util/AbstractSparseBinaryMatrix.java
- src/main/java/org/numenta/nupic/util/FastConnectionsMatrix.java
- src/main/java/org/numenta/nupic/util/FlatMatrix.java
- src/main/java/org/numenta/nupic/util/LowMemorySparseBinaryMatrix.java
- src/main/java/org/numenta/nupic/util/SparseBinaryMatrix.java
- src/test/java/org/numenta/nupic/algorithms/SpatialPoolerTest.java
- src/test/java/org/numenta/nupic/util/SparseBinaryMatrixTest.java
Fixes #376 
optimization to matrix summation calculation.
> rightVecSumAtNZ optimization, changed matrix calls and interface

- .classpath
- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/util/ArrayUtils.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
- src/test/java/org/numenta/nupic/util/ArrayUtilsTest.java
> Add binary array to byte array utility

- .project
> Accidental change to .project file

- src/main/java/org/numenta/nupic/network/Layer.java
- src/main/java/org/numenta/nupic/network/Network.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
> #397 - Adding close() method to Network.

- src/test/java/org/numenta/nupic/network/PALayerTest.java
> #403 - Reorder start() and subscribe() for possible thread race (PALayerTest)

- build.gradle
- pom.xml
Attn: @rhyolight 
Fixes #413 
Release 0.6.6 To Do:
Update:
> Update build files for new release

- build.gradle
- pom.xml
> Update snapshot versions

- build.gradle
- jdoc.sh
- pom.xml
- src/main/java/org/numenta/nupic/algorithms/AnomalyLikelihoodMetrics.java
- src/test/java/org/numenta/nupic/algorithms/AnomalyLikelihoodMetricsTest.java
* Added new packages for serialization
* Changed snapshot version numbering
> Update jdoc script

- src/main/java/org/numenta/nupic/algorithms/TemporalMemory.java
> Remove sys out in crucial place

- src/main/java/org/numenta/nupic/encoders/CategoryEncoder.java
> CategoryEncoder javadoc update

- src/main/java/org/numenta/nupic/algorithms/BitHistory.java
- src/main/java/org/numenta/nupic/algorithms/CLAClassifier.java
> Remove tabs from classifier and bit history formatting

- src/main/java/org/numenta/nupic/algorithms/BitHistory.java
> BitHistory Duty Cycle Rescaling Fix

- src/test/java/org/numenta/nupic/algorithms/SDRClassifierTest.java
> remove obsolete imports

- src/main/java/org/numenta/nupic/algorithms/Anomaly.java
- src/test/java/org/numenta/nupic/algorithms/AnomalyTest.java
- src/test/java/org/numenta/nupic/network/PersistenceAPITest.java
> Changed default return for empty active columns

- src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
- src/main/java/org/numenta/nupic/util/ArrayUtils.java
- src/test/java/org/numenta/nupic/algorithms/SpatialPoolerTest.java
- src/test/java/org/numenta/nupic/util/ArrayUtilsTest.java
> Fixed not filled overlaps array in updateDutyCycles

- src/main/java/org/numenta/nupic/Connections.java
- src/main/java/org/numenta/nupic/algorithms/TemporalMemory.java
- src/main/java/org/numenta/nupic/util/GroupBy2.java
- src/test/java/org/numenta/nupic/QuickTest.java
- vocabulary.dictionary
Fixes #457 
Interim changes having the first successful exact duplicate processing output as the Python version
Not yet ready for merge... Still waiting on https://github.com/numenta/nupic/pull/3307
> Exact Python TM Output Duplication

- src/main/java/org/numenta/nupic/network/Layer.java
- src/test/java/org/numenta/nupic/RunLayer.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
Fixes #475 
* Added test for TM-only logic
* Added ability to run NAPI inside RunLayer utility
> Added new Logic for TM-only Anomaly calcs within NAPI

- .gitignore
- src/main/java/org/numenta/nupic/Connections.java
- src/main/java/org/numenta/nupic/Parameters.java
- src/main/java/org/numenta/nupic/network/Layer.java
- src/test/java/org/numenta/nupic/ConnectionsTest.java
- src/test/java/org/numenta/nupic/algorithms/SpatialPoolerTest.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
- src/test/java/org/numenta/nupic/network/NetworkTestHarness.java
> Added fix for potential radius

- src/main/java/org/numenta/nupic/algorithms/AnomalyLikelihood.java
- src/test/java/org/numenta/nupic/algorithms/AnomalyLikelihoodTest.java
Fixes #487 Ensure that probationary period is set correctly when instantiating AnomalyLikelihood.
> Fixes issue #487

- src/main/java/org/numenta/nupic/algorithms/AnomalyLikelihood.java
- src/test/java/org/numenta/nupic/algorithms/AnomalyLikelihoodTest.java
Fixes #488 to avoid ArrayIndexOutOfBoundsException
> Fixes issue #488

- src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
- src/main/java/org/numenta/nupic/algorithms/TemporalMemory.java
- src/main/java/org/numenta/nupic/util/GroupBy.java
- src/main/java/org/numenta/nupic/util/GroupBy2.java
- src/test/java/org/numenta/nupic/ComputeCycleTest.java
- src/test/java/org/numenta/nupic/util/GroupBy2Test.java
- src/test/java/org/numenta/nupic/util/GroupByTest.java
> Fixes issue #491, use chaschev.lang.Pair instead of JavaFX Pair

- build.gradle
- pom.xml
> Update build.gradle and pom.xml for new snapshot

- src/main/java/org/numenta/nupic/Parameters.java
- src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
- src/main/java/org/numenta/nupic/model/Connections.java
- src/test/java/org/numenta/nupic/algorithms/SpatialPoolerTest.java
- src/test/java/org/numenta/nupic/network/RegionTest.java
Fixes #497 
Fixes #498 
Added 4 zero overlap tests to the SpatialPoolerTest
> Add 4 SP Zero Overlap Tests & Parameter KEY docs

- build.gradle
- pom.xml
> push new release branch

- build.gradle
- pom.xml
- src/main/java/org/numenta/nupic/network/Layer.java
- src/test/java/org/numenta/nupic/datagen/ResourceLocatorTest.java
- src/test/java/org/numenta/nupic/network/LayerTest.java
- src/test/java/org/numenta/nupic/network/NetworkTest.java
- src/test/java/org/numenta/nupic/util/ConditionTest.java
Fixes #502 
Rolling ahead to 0.6.11 in order to fix deployment to Maven Central
> Gradle build fix

- README.md
> Updated location of Java docs in readme

- src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java
> Tab removal

- build.gradle
- pom.xml
- src/test/java/org/numenta/nupic/FieldMetaTypeTest.java
> Update for release v0.6.13 alpha

- src/test/java/org/numenta/nupic/network/PersistenceAPITest.java
- src/test/java/org/numenta/nupic/util/UniversalRandomTest.java
Addresses the two identified causes of test case failures in Windows
> Fixes #522

- src/main/java/org/numenta/nupic/network/sensor/FileSensor.java
Fixes #547 
Added windows path parsing fix.
> Added parsing for windows case
