numenta/htm.java

src/test/java/org/numenta/nupic/encoders/RandomDistributedScalarEncoderTest.java

Removing one test because testing the RNG is not part of the scope of this test - and we cannot assure that the RNG will initialize the default seed to different values.
fixes #167

testing the RNG is not part of the scope 

---

src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java

The if condition was checking if minVal is an NaN twice instead of checking for minVal and maxVal. Hence, made the correction.
Fixes #201

if condition corrected to check NaN for minVal and maxVal

---

src/main/java/org/numenta/nupic/datagen/ResourceLocator.java

Fixes #225
The unit test org.numenta.nupic.network.sensor.BatchedCsvStreamTest failed on my Windows machine.
The error was caused by a leading slash at the beginning of the URL returned by org.numenta.nupic.datagen.ResourceLocator.java:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Helge/Development/projects/src/htm.java/build/resources/test/rec-center-hourly.csv
at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
```
(The error message is a bit irritating, the problem is /C:/... which should be C:/...)
The fix works fine on both Windows and Linux.

Fixed ResourceLocator bug returning wrong resource locations on Windows

---

src/main/java/org/numenta/nupic/Connections.java
src/main/java/org/numenta/nupic/algorithms/CLAClassifier.java
src/main/java/org/numenta/nupic/network/Layer.java
src/main/java/org/numenta/nupic/network/Network.java
src/main/java/org/numenta/nupic/network/Region.java
src/main/java/org/numenta/nupic/research/ComputeCycle.java
src/main/java/org/numenta/nupic/research/TemporalMemory.java
src/main/java/org/numenta/nupic/util/NamedTuple.java
src/main/java/org/numenta/nupic/util/Tuple.java
src/test/java/org/numenta/nupic/network/LayerTest.java
src/test/java/org/numenta/nupic/network/NetworkTest.java
src/test/java/org/numenta/nupic/network/RegionTest.java
src/test/java/org/numenta/nupic/research/TemporalMemoryTest.java
src/test/java/org/numenta/nupic/util/TupleTest.java

This commit adds a bunch of fixes, and tune ups - namely:
1. CLAClassifier init fix for multiple steps 
2. Layer class initiated TemporalMemory wrongly.
3. Added ability to reset a Network and reset the record num counter from a Network
4. For immutable Tuples, cache the hashcode and use it for "equals()" method instead of churning through internal objects.
Fixes #233 
Fixes #234 
Fixes #235 
Fixes #236 
Fixes #241

Classifier fixes, Layer fixes, Tuple speedup

---

src/main/java/org/numenta/nupic/network/Network.java
src/test/java/org/numenta/nupic/network/NetworkTest.java

Fixes #260 
Added ability to get returned Inference from a network compute call in a synchronous fashion (directly).

Synchronous compute

---

src/main/java/org/numenta/nupic/FieldMetaType.java
src/main/java/org/numenta/nupic/network/sensor/HTMSensor.java
src/test/java/org/numenta/nupic/network/NetworkTestHarness.java
src/test/java/org/numenta/nupic/network/sensor/HTMSensorTest.java
vocabulary.dictionary

Adding GeospatialCoordinateEncoder Builder configuration

---

src/main/java/org/numenta/nupic/Parameters.java
src/main/java/org/numenta/nupic/encoders/DateEncoder.java
src/main/java/org/numenta/nupic/encoders/MultiEncoderAssembler.java
src/test/java/org/numenta/nupic/encoders/DateEncoderTest.java

Fixes #358. hourOfWeek encoder is a copy of timeOfDay, using 168 as a max value and calculating a floating point input to its periodic scalar encoder, which is the number of hours since 00:00 on Monday (to the nearest second).

Added hourOfWeek to DateEncoder

---

src/main/java/org/numenta/nupic/util/ArrayUtils.java
src/main/java/org/numenta/nupic/util/FastConnectionsMatrix.java
src/main/java/org/numenta/nupic/util/FlatArrayMatrix.java
src/main/java/org/numenta/nupic/util/LowMemorySparseBinaryMatrix.java
src/main/java/org/numenta/nupic/util/SetSparseMatrix.java
src/main/java/org/numenta/nupic/util/SparseBinaryMatrix.java
src/main/java/org/numenta/nupic/util/SparseBinaryMatrixSupport.java
src/main/java/org/numenta/nupic/util/SparseMatrix.java
src/main/java/org/numenta/nupic/util/SparseMatrixSupport.java
src/main/java/org/numenta/nupic/util/SparseObjectMatrix.java
src/test/java/org/numenta/nupic/util/SparseBinaryMatrixTest.java

- Add FastConnectionsMatrix for input connections (sparse).
- Remove sparse map from SparseBinaryMatrixSupport.
- Remove sparse map usage from SparseBinaryMatrix.
Fix #355

Add a  low memory and fast implementation for input connections matrix.

---

src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
src/test/java/org/numenta/nupic/util/ArrayUtilsTest.java

Fixes #354 
Here I am using streams. This is not a replacement for nupic python argpartition function. I have measured the performance gain with this change. It gives atleast 4000% performance gain. Please review

From NuPIC: Can inhibitColumnsGlobal() execute without sort() ? #354 (#365) 

---

src/main/java/org/numenta/nupic/util/ArrayUtils.java
src/main/java/org/numenta/nupic/util/NearestNeighbor.java
src/test/java/org/numenta/nupic/util/ArrayUtilsTest.java

Fixes #377 
@rhyolight Please accept...

Added more utility methods in preparation for KNN dev

---

.project
pom.xml
src/test/java/org/numenta/nupic/monitor/mixin/MetricsTraceTest.java

Fixes #388 
Making this change, to make org.numenta.nupic.network.LayerTest, run on any IDE. LayerTest was failing on Intellij Idea, due to missing dependency. Now, we can potentially clean up jmh-core dependency from .classpath file and libs directory.

Moving dependency from .classpath and libs directory to maven pom.xml

---

build.gradle

Fixes #392
Incremented version of the gradle shadow plugin to 1.2.3, which contains a fix for compatibility with gradle 2.11 and higher.

Incremented version of the gradle shadow plugin to 1.2.3

---

src/main/java/org/numenta/nupic/monitor/mixin/MetricsTrace.java

Fixes #394
Added Locale.US to ensure that the tests were executed using dot decimal punctuation only.

Added Locale.US to MetricsTrace.java

---

src/main/java/org/numenta/nupic/network/sensor/BatchedCsvStream.java
src/test/java/org/numenta/nupic/network/LayerTest.java
src/test/java/org/numenta/nupic/network/NetworkTest.java

Fixes #403 
Hopefully... I don't have OpenJDK, but I highly suspect the following changes will solve this.

Reorder start() and subscribe() for possible thread race

---

src/test/java/org/numenta/nupic/network/LayerTest.java

Fixes #408 removed testExplicitCloseFailure from LayerTest.java
Fixes build which has test that failed under Linux RHEL 7

Removing malformed test from LayerTest

---

build.gradle
pom.xml
src/main/java/org/numenta/nupic/network/Network.java
src/main/java/org/numenta/nupic/serialize/HTMObjectInput.java
src/main/java/org/numenta/nupic/serialize/HTMObjectOutput.java
src/main/java/org/numenta/nupic/serialize/SerializerCore.java
src/test/java/org/numenta/nupic/serialize/HTMObjectInputOutputTest.java

Fixes #417 
Fixes #418 
Support not halting the Network when serializing it during non-threaded use. This support is built in to the checkpointing mechanism so halt doesn't have to be called, but in the case where a library has its own checkpointing mechanism (i.e. Flink), this patch will support that use case if the Network is not in threaded mode. 
If the Network **is** in threaded mode then users are forced to use the built in checkpointing mechanism until such time as a need develops to allow some flexibility with that option.

Slight persistence patch and HTMObjectIn/Output constructor change.

---

src/test/java/org/numenta/nupic/network/AlgorithmDeterminacyTest.java
src/test/java/org/numenta/nupic/network/LayerTest.java
src/test/java/org/numenta/nupic/network/NetworkTest.java
src/test/java/org/numenta/nupic/network/ObservableTestBase.java
src/test/java/org/numenta/nupic/network/ObservableTestBaseTest.java
src/test/java/org/numenta/nupic/network/PersistenceAPITest.java
src/test/java/org/numenta/nupic/network/PlaygroundTest.java
src/test/java/org/numenta/nupic/network/RegionTest.java

fixes #434 
* Added TestObserver solution found by @fergalbyrne 
* Inserted TestObserver in all relevant tests 
* Created new test base class to handle new test remedy 
@rhyolight please approve

Junit observer fix

---

src/main/java/org/numenta/nupic/network/Layer.java
src/test/java/org/numenta/nupic/network/NetworkConsistencyTest.java

Fixes #436 
```feedForwardActiveColumns``` is now set from a fresh int[] and not reusing the pointer to the stale field.
Also adding the ```NetworkConsistencyTest``` class to test all outputs are isolated.

Fixed bug where feedForwardActiveColumns was getting overwritten

---

src/main/java/org/numenta/nupic/Connections.java
src/main/java/org/numenta/nupic/Parameters.java
src/main/java/org/numenta/nupic/algorithms/AnomalyLikelihood.java
src/main/java/org/numenta/nupic/algorithms/SpatialPooler.java
src/test/java/org/numenta/nupic/ConnectionsTest.java
src/test/java/org/numenta/nupic/algorithms/AnomalyLikelihoodMetricsTest.java
src/test/java/org/numenta/nupic/util/NearestNeighborTest.java

Fixes #477 
Added method ```doSpatialPoolerPostInit()``` method to correctly calculate these values _after_ the Parameters get applied.
Added a test to show the difference in configuration state after using this method.

Added Post Init method to fix 2 derived variables; added test for same

---

src/main/java/org/numenta/nupic/algorithms/CLAClassifier.java

Fixes #505 
I fixed a typo about the return type and the example in the comment using mixed decimal point styles.

Fixed documentation typo in CLA Classifier

---

src/main/java/org/numenta/nupic/model/Synapse.java
src/main/java/org/numenta/nupic/network/Layer.java
src/test/java/org/numenta/nupic/model/SynapseTest.java

Fixes #513. This PR changes use of `==` operator to `Class.isAssignableFrom` method in `Layer.java`.

Changed use of "==" operator to Class.isAssignableFrom method

---

src/main/java/org/numenta/nupic/FieldMetaType.java
src/test/java/org/numenta/nupic/FieldMetaTypeTest.java

Fixes #517 
Added code to correct the return value of the BOOLEAN ```FieldMetaType.decodeType()``` method.

Boolean meta type fix

---

src/main/java/org/numenta/nupic/network/Layer.java
src/test/java/org/numenta/nupic/network/PersistenceAPITest.java

Notify observers of uncaught exceptions in layer thread, this will fail a test case when checkObserver is being called.
In the affected test case, force UTC timezone for a more consistent test experience.

Fixes #524
